site_name: DiSky Wiki
theme:
  name: material
  icon:
    logo: simple/discord
  palette:
    scheme: slate
    primary: orange
    accent: amber
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
repo_url: https://github.com/DiSkyOrg/DiSky

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/main.css

extra:
  status:
    new: 'Recently added'
    deprecated: 'Deprecated'

plugins:
  - search
  - include_dir_to_nav
  - badges
  - macros:
      include_dir: macros
      j2_block_start_string: "[[[%"
      j2_block_end_string: "%]]]"
      j2_variable_start_string: "[[["
      j2_variable_end_string: "]]]"

nav:
  - 'Wiki':
      - 'Home': home.md
      - 'Getting Started':
          - 'Installation': getting-started/0-installation.md
          - 'Bot Creation': getting-started/1-bot-creation.md
          - 'Bot Loading': getting-started/2-bot-loading.md
          - 'Frequently Asked Questions (FAQ)': getting-started/faq.md
      - 'Basic Stuff': basic-stuff
      - 'Advanced Stuff': advanced-stuff
  - 'Modules': modules
  - 'Documentation':
      - 'Effects': docs/effects.md
      - 'Events': docs/events.md
      - 'Expressions': docs/expressions.md
      - 'Conditions': docs/conditions.md
      - 'Types': docs/types.md
      - 'Sections': docs/sections.md
      - 'Modules':
          - 'LavaPlayer': docs/lavaplayer.md
          - 'TranSkript': docs/transkript.md
  - 'SkImage2': skimage
  #- 'Create an Addon':
  #    - addons/getting-started.md
  - 'BooSK':
      - 'Getting Started': boosk/getting-started.md
      - 'Create a Book': boosk/create-a-book.md